### ISSUE TITLE
Pi character doesn't display properly on Trig Review page in Chrome

### ISSUE THREAD

**Issue by dbeckwith** [jackschaedler/circles-sines-signals#10]
Only shows a question mark box where the pi character should be in the diagram. Chrome 41.0.2272.76.

**Comment by dbeckwith** [comment]
Seems like the character wasn't encoded properly in the [source file](https://github.com/jackschaedler/circles-sines-signals/blob/master/js/phasor_trig.js#L179).

**Comment by SSteve** [comment]
Pi shows up as a box in Safari on an iPad.

**Comment by jackschaedler** [comment]
Will get this sorted out this weekend. Thanks for the reports, and sorry for the long wait!

**Comment by jackschaedler** [comment]
This shows up properly for me know on iPad. I was using the too-fancy version of PI in the javascript file.
