### ISSUE TITLE
Incorrect use of `factoid`

### ISSUE THREAD

**Issue by bluesmoon** [jackschaedler/circles-sines-signals#11]
On the correlation page: http://jackschaedler.github.io/circles-sines-signals/dotproduct2.html the usage of `factoid` should be corrected.

The term `factoid` typically represents something that appears to be true, but is not actually true.  The term `tidbit` might be a better use here.

PS.  Really enjoying this lesson.

**Comment by jackschaedler** [comment]
Brilliant, this totally made my day. I was just reading an article on usage this morning!

I had no idea that factoid had this meaning. Will update tomorrow!

**Comment by jackschaedler** [comment]
Thanks again, should be fixed now.
