### ISSUE TITLE
Unit circle digrams not interactive

### ISSUE THREAD

**Issue by mgold** [jackschaedler/circles-sines-signals#14]
http://jackschaedler.github.io/circles-sines-signals/trig_review.html

The slider seems to trigger `Uncaught ReferenceError: GET_TRIG_PHASE is not defined` and the digram does not change in response. Possibly related to #2. If it worked before, it's probably an easy fix.

**Comment by jackschaedler** [comment]
Thanks for the issue. Which browser are you using when you see this behavior?

**Comment by mgold** [comment]
Chrome 41, Yosemite.... but it seems to be working now and nothing is logged to the console. #2 is also working for me again (except I can't hear the sound? Quite possibly a fluke on my end.).

Closing as it works now. Hopefully you changed something rather than it being intermittent.

**Comment by justinlevi** [comment]
@jackschaedler @mgold I believe this issue should be reopened actually. I'm attaching a screen capture image showing the issue still on the latest mac chrome. I'm also uploading a screen capture video to dropbox (link below)

https://dl.dropboxusercontent.com/u/12722991/circles-signes-signals.mp4

![screen shot 2015-05-16 at 8 52 09 am](https://cloud.githubusercontent.com/assets/1117989/7666206/bc352cce-fba9-11e4-90a5-66d54e5ff661.jpg)

I *think* this is a race condition where the `GET_TRIG_PHASE()` is not being defined in time at the bottom of trig_review.html on line 144. 

phasor_trig.js is being included on line 98 so it might be possible for the draw function on line 246 to fire prior to the variable declarations at the bottom of the html

**Comment by mgold** [comment]
That's a really compelling explanation and an excellent reproduction. Setting a breakpoint to defeat a race condition - neat trick. Also: I'm not crazy!

**Comment by jackschaedler** [comment]
Just pushed a quick fix. Would be great if you all could give it a test!

**Comment by mgold** [comment]
Seems good, but of course it's hard to know for sure.

**Comment by justinlevi** [comment]
Finally had a minute to check this out. All looks good on this end.

**Comment by jackschaedler** [comment]
Ok, thanks everyone! I'm going to close this for now.
