### ISSUE TITLE
Increasing vibration frequency shouldn't increase velocity

### ISSUE THREAD

**Issue by SSteve** [jackschaedler/circles-sines-signals#18]
In figure 1 on https://jackschaedler.github.io/circles-sines-signals/sound.html, increasing the vibration frequency makes the waves move faster through the air. This isn't physically accurate. All frequencies move at the speed of sound. When the vibration speed changes, the wavelength should change and the velocity should remain constant.

It's interesting to imagine what sound would be like if velocity was proportional to frequency. The higher harmonics of a sound would reach the listener before the fundamental frequency. It would be an incoherent mess. But if that's how the physical world worked, maybe our brains would have evolved to interpret sound differently.

**Comment by jackschaedler** [comment]
Hi Steve,

Thanks for reporting this. It's embarrassing that I haven't fixed this yet, and I will use this issue as extra motivation to get this sorted out soon. That is a fun thought experiment though!

**Comment by SSteve** [comment]
As I continued through the site, I saw that velocity is handled correctly on https://jackschaedler.github.io/circles-sines-signals/sincos.html. Of course, that one doesn't also have the air molecule illustration to deal with.

**Comment by jackschaedler** [comment]
Ok, I've updated the animation to properly show the inverse relationship between wavelength and frequency. Thanks for calling me out on this. Re-open if you find any problems.

http://jackschaedler.github.io/circles-sines-signals/sound.html
