### ISSUE TITLE
Frequency distribution doesn't appear for samples when you play them

### ISSUE THREAD

**Issue by javajosh** [jackschaedler/circles-sines-signals#2]
The frequency distribution doesn't appear for samples when you play them at http://jackschaedler.github.io/circles-sines-signals/sound2.html

The axes are drawn, but nothing is drawn within the plot when you play a sample. Would have expected a histogram or similar.

OSX 10.10.2/Chrome 39

**Comment by michalparkola** [comment]
It's related to the variable NEW_DATA_AVAILABLE being missing in the update function in spectrum.js.

**Comment by mgold** [comment]
I also ran into this. Hope you get a chance to fix it.

**Comment by mgold** [comment]
I can see the plot and hear the sound now (so it looks and sounds good to me).

**Comment by jackschaedler** [comment]
Just pushed a fix. Give it a shot and let me know if you run into any problems!

**Comment by mgold** [comment]
Different error, but the distribution doesn't reset when the tone ends. The race condition seems fixed.

**Comment by jackschaedler** [comment]
Ok, I''m going to close this one for now. I actually like that the spectrum doesn't reset when the tone ends, so I'll keep it like this.
