### ISSUE TITLE
Complex plane example initialized with inconsistent coordinates

### ISSUE THREAD

**Issue by weslord** [jackschaedler/circles-sines-signals#22]
https://jackschaedler.github.io/circles-sines-signals/complex.html

The graphical representation of the complex plane starts with the point at +0.71 + 0.71i, but the text says +0.50 + 0.50i.

Once you interact, the text updates to match the graph, but until you do they are inconsistent with one another.

**Comment by weslord** [comment]
... and I just noticed there's already a pull request for this (#20).

**Comment by jackschaedler** [comment]
Fixed by #20
