### ISSUE TITLE
typo on "sine wave properties" page

### ISSUE THREAD

**Issue by LGoodacre** [jackschaedler/circles-sines-signals#26]
I LOVED reading your DFT guide. I wouldn't have believed that it was possible to learn so much about this topic in little over an hour, but the visualizations, together with your explanations, really make it light work. More of the same please!

There's a tiny typo at the bottom of this page: https://jackschaedler.github.io/circles-sines-signals/sine_wave_properties.html

You've written "the" twice in the third to last page. Just search for "the the" and you'll find it.

**Comment by rgetz** [comment]
I think this has been fixed at https://github.com/jackschaedler/circles-sines-signals/blob/master/sine_wave_properties.html#L217, it's just the resulting html isn't updated.

**Comment by jackschaedler** [comment]
Thanks for reporting, and sorry for the incredibly late response! This should be fixed now.
