### ISSUE TITLE
No sound on the Sound page on Safari 13.0

### ISSUE THREAD

**Issue by erynofwales** [jackschaedler/circles-sines-signals#29]
I'm playing with the examples on the Sound page in Safari 13.0 and there's no sound. I looked at https://caniuse.com/#search=web-audio and it says Safari supports Web Audio with the `webkit` vendor prefix.

I do get sound on the Timbre page though.

**Comment by jackschaedler** [comment]
Thanks for reporting, and sorry for the very late response! This should be fixed now.
