### ISSUE TITLE
Math formulas don't load on https; work fine on http

### ISSUE THREAD

**Issue by mynamewastaken** [jackschaedler/circles-sines-signals#6]
On https://jackschaedler.github.io/circles-sines-signals/notation.html I see:

    $$ \mathrm{DFT}[k] = \sum_{n=0}^{N-1} \mathrm{x}[n] \cdot e^{-\varphi\mathrm{i}} \\ where \quad \varphi = k \frac{n}{N} 2\pi $$

On jackschaedler.github.io/circles-sines-signals/notation.html, it loads fine.

**Comment by schoen** [comment]
It would be possible to fix this by changing the http://cdn.mathjax.org/ references to https://cdn.mathjax.org/ (which would also work OK for people who are accessing the underlying site over HTTP). It's a problem with mixed-content blocking.

https://developer.mozilla.org/en-US/docs/Security/MixedContent/How_to_fix_website_with_mixed_content

**Comment by jackschaedler** [comment]
Fixed on master

**Comment by mynamewastaken** [comment]
Works perfectly, thanks!
