### ISSUE TITLE
Customizing/changing this primer

### ISSUE THREAD

**Issue by diego898** [jackschaedler/circles-sines-signals#9]
Hello,

I am interested in using this as a starting point for notes for a class I am teaching. Was there a tool you used to build the pages themselves? Some theme/framework? Im just wondering if I start editing the HTML directly from this repository, or I start from using a tool.

Thanks!

**Comment by jackschaedler** [comment]
I just hand coded all of the pages using HTML, CSS and D3.js. Keep me updated on the class! I'd love to hear what the students think!
